spring.application.name=an-traein

spring.datasource.url=jdbc:postgresql://localhost:5432/an_traein
spring.datasource.username=postgres
spring.datasource.password=357fbeb2918a465b963a898985eadfd9

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
